links_list = [
    # category_id -> 2:
    # {'2': 'https://arbuz.kz/ru/almaty/catalog/cat/20666-chernyi_chai#/'},
    # {'3': 'https://arbuz.kz/ru/almaty/catalog/cat/20647-zel_nyi_chai#/'},
    # {'4': 'https://arbuz.kz/ru/almaty/catalog/cat/203902-travyanye_i_fruktovye_chai#/'},
    # {'5': 'https://arbuz.kz/ru/almaty/catalog/cat/20608-rastvorimyi_kofe#/'},
    # {'6': 'https://arbuz.kz/ru/almaty/catalog/cat/20627-molotyi_kofe#/'},
    # {'7': 'https://arbuz.kz/ru/almaty/catalog/cat/20637-kofe_v_z_rnah#/'},
    # {'8': 'https://arbuz.kz/ru/almaty/catalog/cat/196459-kofe_v_kapsulah_dlya_kofemashin#/'},
    # {'9': 'https://arbuz.kz/ru/almaty/catalog/cat/20603-kakao#/'},
    # {'10': 'https://arbuz.kz/ru/almaty/catalog/cat/207217-cikorii#/'},
    # {'11': 'https://arbuz.kz/ru/almaty/catalog/cat/224648-kisel#/'},
    # {'12': 'https://arbuz.kz/ru/almaty/catalog/cat/20741-soki_nektary#/'},
    # {'13': 'https://arbuz.kz/ru/almaty/catalog/cat/224613-soki_pryamogo_otzhima#/'},
    # {'14': 'https://arbuz.kz/ru/almaty/catalog/cat/199332-morsy_kompoty#/'},
    # {'15': 'https://arbuz.kz/ru/almaty/catalog/cat/25328-holodnyi_chai_kvas_kombucha#/'},
    # {'16': 'https://arbuz.kz/ru/almaty/catalog/cat/25324-negazirovannaya#/'},
    # {'17': 'https://arbuz.kz/ru/almaty/catalog/cat/20698-gazirovannaya#/'},
    # {'18': 'https://arbuz.kz/ru/almaty/catalog/cat/225147-mineralnaya#/'},
    # {'19': 'https://arbuz.kz/ru/almaty/catalog/cat/25325-gazirovannye_napitki#/'},
    # {'20': 'https://arbuz.kz/ru/almaty/catalog/cat/205399-energeticheskie_napitki#/'},
    # {'21': 'https://arbuz.kz/ru/almaty/catalog/cat/224698-kofeinye_napitki#/'},
    # {'22': 'https://arbuz.kz/ru/almaty/catalog/cat/224930-toniki#/'},
    # category_id -> 3:
    {'33': 'https://arbuz.kz/ru/almaty/catalog/cat/20050-moloko#/'},
    {'34': 'https://arbuz.kz/ru/almaty/catalog/cat/224177-rastitelnoe_moloko#/'},
    {'35': 'https://arbuz.kz/ru/almaty/catalog/cat/20040-slivochnoe_maslo#/'},
    {'36': 'https://arbuz.kz/ru/almaty/catalog/cat/224760-margarin_spred#/'},
    {'37': 'https://arbuz.kz/ru/almaty/catalog/cat/20077-slivki#/'},
    {'38': 'https://arbuz.kz/ru/almaty/catalog/cat/74410-fermerskoe_moloko#/'},
    {'39': 'https://arbuz.kz/ru/almaty/catalog/cat/20089-smetana#/'},
    {'40': 'https://arbuz.kz/ru/almaty/catalog/cat/224700-suhoe_moloko#/'},
    {'41': 'https://arbuz.kz/ru/almaty/catalog/cat/20072-sgush_nnoe_moloko#/'},
    {'42': 'https://arbuz.kz/ru/almaty/catalog/cat/20016-kislomolochnye_napitki#/'},
    {'43': 'https://arbuz.kz/ru/almaty/catalog/cat/20099-tvorog#/'},
    {'44': 'https://arbuz.kz/ru/almaty/catalog/cat/19987-gustye_iogurty#/'},
    {'45': 'https://arbuz.kz/ru/almaty/catalog/cat/20008-iogurty_pitevye#/'},
    {'46': 'https://arbuz.kz/ru/almaty/catalog/cat/224565-syrki#/'},
    {'47': 'https://arbuz.kz/ru/almaty/catalog/cat/224518-molochnye_kokteili#/'},
    {'48': 'https://arbuz.kz/ru/almaty/catalog/cat/206746-tvorozhnye_deserty#/'},
    {'49': 'https://arbuz.kz/ru/almaty/catalog/cat/20184-tv_rdyi#/'},
    {'50': 'https://arbuz.kz/ru/almaty/catalog/cat/224577-myagkii#/'},
    {'51': 'https://arbuz.kz/ru/almaty/catalog/cat/20173-rassolnyi#/'},
    {'52': 'https://arbuz.kz/ru/almaty/catalog/cat/20161-s_plesenyu#/'},
    {'53': 'https://arbuz.kz/ru/almaty/catalog/cat/143610-tvorozhnyi#/'},
    {'54': 'https://arbuz.kz/ru/almaty/catalog/cat/20164-plavlenyi#/'},
    {'55': 'https://arbuz.kz/ru/almaty/catalog/cat/225028-kozii_ovechii_#/'},
    {'56': 'https://arbuz.kz/ru/almaty/catalog/cat/225029-chechil#/'},
    {'57': 'https://arbuz.kz/ru/almaty/catalog/cat/224600-syrnye_produkty#/'},
    {'58': 'https://arbuz.kz/ru/almaty/catalog/cat/225082-belorusskie_syry#/'},
    {'59': 'https://arbuz.kz/ru/almaty/catalog/cat/20114-kurinye#/'},
    # category_id -> 4:
    {'60': 'https://arbuz.kz/ru/almaty/catalog/cat/19957-svezhaya_ryba#/'},
    {'61': 'https://arbuz.kz/ru/almaty/catalog/cat/19981-sol_naya_ryba#/'},
    {'62': 'https://arbuz.kz/ru/almaty/catalog/cat/224532-preservy#/'},
    {'63': 'https://arbuz.kz/ru/almaty/catalog/cat/19962-zamorozhennaya_ryba#/'},
    {'64': 'https://arbuz.kz/ru/almaty/catalog/cat/19969-kopch_naya_ryba#/'},
    {'65': 'https://arbuz.kz/ru/almaty/catalog/cat/19974-moreprodukty#/'},
    {'66': 'https://arbuz.kz/ru/almaty/catalog/cat/19984-ikra#/'},
    {'67': 'https://arbuz.kz/ru/almaty/catalog/cat/224617-ikornye_zakuski#/'},
    {'68': 'https://arbuz.kz/ru/almaty/catalog/cat/225003-krabovye_palochki#/'},
    {'69': 'https://arbuz.kz/ru/almaty/catalog/cat/225018-pasta_iz_ryby_i_moreproduktov#/'},
    # category_id -> 5:
    {'70': 'https://arbuz.kz/ru/almaty/catalog/cat/19412-bahchevye#/'},
    {'71': 'https://arbuz.kz/ru/almaty/catalog/cat/19454-yagody_svezhie#/'},
    {'72': 'https://arbuz.kz/ru/almaty/catalog/cat/19426-ekzoticheskie#/'},
    {'73': 'https://arbuz.kz/ru/almaty/catalog/cat/19419-citrusovye#/'},
    {'74': 'https://arbuz.kz/ru/almaty/catalog/cat/19432-yabloki_i_grushi#/'},
    {'75': 'https://arbuz.kz/ru/almaty/catalog/cat/19415-vinograd#/'},
    {'76': 'https://arbuz.kz/ru/almaty/catalog/cat/19444-frukty_prochie#/'},
    {'77': 'https://arbuz.kz/ru/almaty/catalog/cat/19383-pomidory#/'},
    {'78': 'https://arbuz.kz/ru/almaty/catalog/cat/224936-tykva#/'},
    {'79': 'https://arbuz.kz/ru/almaty/catalog/cat/19362-luk_chesnok#/'},
    {'80': 'https://arbuz.kz/ru/almaty/catalog/cat/19346-korneplody#/'},
    {'81': 'https://arbuz.kz/ru/almaty/catalog/cat/19340-kapusta#/'},
    {'82': 'https://arbuz.kz/ru/almaty/catalog/cat/19373-perec#/'},
    {'83': 'https://arbuz.kz/ru/almaty/catalog/cat/19370-ogurcy#/'},
    {'84': 'https://arbuz.kz/ru/almaty/catalog/cat/224608-griby#/'},
    {'85': 'https://arbuz.kz/ru/almaty/catalog/cat/19389-baklazhany_kabachki_sparzha#/'},
    {'86': 'https://arbuz.kz/ru/almaty/catalog/cat/224609-solenya#/'},
    {'87': 'https://arbuz.kz/ru/almaty/catalog/cat/224629-zakuska_iz_morskoi_kapusty#/'},
    {'88': 'https://arbuz.kz/ru/almaty/catalog/cat/224643-kukuruza_goroh#/'},
    {'89': 'https://arbuz.kz/ru/almaty/catalog/cat/25416-zelen#/'},
    {'90': 'https://arbuz.kz/ru/almaty/catalog/cat/225333-salaty_miks#/'},
    {'91': 'https://arbuz.kz/ru/almaty/catalog/cat/225334-mikrozelen#/'},
    {'92': 'https://arbuz.kz/ru/almaty/catalog/cat/19786-orehi#/'},
    {'93': 'https://arbuz.kz/ru/almaty/catalog/cat/19798-suhofrukty#/'},
    {'94': 'https://arbuz.kz/ru/almaty/catalog/cat/218350-fruktovye_sneki#/'},
    # category_id -> 6:
    {'95': 'https://arbuz.kz/ru/almaty/catalog/cat/225202-vtorye_blyuda#/'},
    {'96': 'https://arbuz.kz/ru/almaty/catalog/cat/225203-salaty#/'},
    {'97': 'https://arbuz.kz/ru/almaty/catalog/cat/225089-supy_zamorozhennye#/'},
    {'98': 'https://arbuz.kz/ru/almaty/catalog/cat/225299-detskie_obedy#/'},
    {'99': 'https://arbuz.kz/ru/almaty/catalog/cat/225302-deserty_i_napitki#/'},
    {'100': 'https://arbuz.kz/ru/almaty/catalog/cat/225291-pp-lanchi_i_deserty#/'},
    {'101': 'https://arbuz.kz/ru/almaty/catalog/cat/225290-deserty#/'},
    {'102': 'https://arbuz.kz/ru/almaty/catalog/cat/225311-svezhaya_vypechka#/'},
    # category_id -> 7:
    {'103': 'https://arbuz.kz/ru/almaty/catalog/cat/225273-produkty_iz_kozego_moloka#/'},
    {'104': 'https://arbuz.kz/ru/almaty/catalog/cat/225274-molochnaya_produkciya_yaica#/'},
    {'105': 'https://arbuz.kz/ru/almaty/catalog/cat/225270-syr#/'},
    {'106': 'https://arbuz.kz/ru/almaty/catalog/cat/225271-myaso#/'},
    {'107': 'https://arbuz.kz/ru/almaty/catalog/cat/225280-ptica#/'},
    {'108': 'https://arbuz.kz/ru/almaty/catalog/cat/225285-delikatesy#/'},
    {'109': 'https://arbuz.kz/ru/almaty/catalog/cat/225279-zamorozhennye_produkty#/'},
    {'110': 'https://arbuz.kz/ru/almaty/catalog/cat/225272-bakaleya#/'},
    {'111': 'https://arbuz.kz/ru/almaty/catalog/cat/225297-solenya_i_zagotovki#/'},
    {'112': 'https://arbuz.kz/ru/almaty/catalog/cat/225306-sousy#/'},
    {'114': 'https://arbuz.kz/ru/almaty/catalog/cat/225308-rastitelnoe_maslo#/'},
    {'115': 'https://arbuz.kz/ru/almaty/catalog/cat/225309-sladosti#/'},
    # category_id -> 8:
    {'118': 'https://arbuz.kz/ru/almaty/catalog/cat/173816-gus_utka_krolik#/'},
    {'119': 'https://arbuz.kz/ru/almaty/catalog/cat/19914-kurica#/'},
    {'120': 'https://arbuz.kz/ru/almaty/catalog/cat/19929-indeika#/'},
    {'121': 'https://arbuz.kz/ru/almaty/catalog/cat/225137-kurica_ohlazhd_nnaya#/'},
    {'122': 'https://arbuz.kz/ru/almaty/catalog/cat/19932-govyadina_zamorozhennaya#/'},
    {'123': 'https://arbuz.kz/ru/almaty/catalog/cat/224780-govyadina_ohlazhdennaya#/'},
    {'124': 'https://arbuz.kz/ru/almaty/catalog/cat/19945-baranina#/'},
    {'125': 'https://arbuz.kz/ru/almaty/catalog/cat/215627-konina#/'},
    {'126': 'https://arbuz.kz/ru/almaty/catalog/cat/19948-svinina#/'},
    {'127': 'https://arbuz.kz/ru/almaty/catalog/cat/208822-steik#/'},
    {'128': 'https://arbuz.kz/ru/almaty/catalog/cat/19951-shashlyki_marinady_barbekyu#/'},
    # category_id -> 9:
    {'129': 'https://arbuz.kz/ru/almaty/catalog/cat/224759-celnozernovoi#/'},
    {'130': 'https://arbuz.kz/ru/almaty/catalog/cat/201883-bezglyutenovaya_vypechka#/'},
    {'131': 'https://arbuz.kz/ru/almaty/catalog/cat/20144-hleb#/'},
    {'132': 'https://arbuz.kz/ru/almaty/catalog/cat/224913-hleb_dlya_sendvichei_i_buterbrodov#/'},
    {'133': 'https://arbuz.kz/ru/almaty/catalog/cat/224914-lavash_pita_lepeshki#/'},
    {'134': 'https://arbuz.kz/ru/almaty/catalog/cat/188153-vypechka#/'},
    {'135': 'https://arbuz.kz/ru/almaty/catalog/cat/224931-tartaletki_grissini#/'},
    # category_id -> 10:
    {'137': 'https://arbuz.kz/ru/almaty/catalog/cat/19860-var_nye_kolbasy#/'},
    {'138': 'https://arbuz.kz/ru/almaty/catalog/cat/224902-vetchina#/'},
    {'139': 'https://arbuz.kz/ru/almaty/catalog/cat/224903-var_nye_kolbasy_bez_svininy_halal_#/'},
    {'140': 'https://arbuz.kz/ru/almaty/catalog/cat/224906-var_no-kopch_nye_kolbasy#/'},
    {'141': 'https://arbuz.kz/ru/almaty/catalog/cat/224907-polukopch_nye_kolbasy#/'},
    {'142': 'https://arbuz.kz/ru/almaty/catalog/cat/224908-syrokopch_nye_syrovyalenye_kolbasy#/'},
    {'143': 'https://arbuz.kz/ru/almaty/catalog/cat/224909-kopchenye_kolbasy_bez_svininy_halal_#/'},
    {'144': 'https://arbuz.kz/ru/almaty/catalog/cat/19899-narezki#/'},
    {'145': 'https://arbuz.kz/ru/almaty/catalog/cat/224910-bekon#/'},
    {'146': 'https://arbuz.kz/ru/almaty/catalog/cat/224911-myaso_kopch_noe_vyalenoe#/'},
    {'147': 'https://arbuz.kz/ru/almaty/catalog/cat/224912-ptica_kopch_naya#/'},
    {'148': 'https://arbuz.kz/ru/almaty/catalog/cat/225081-belorusskie_kolbasy#/'},
    {'149': 'https://arbuz.kz/ru/almaty/catalog/cat/19886-sosiski#/'},
    {'150': 'https://arbuz.kz/ru/almaty/catalog/cat/224904-sardelki_shpikachki#/'},
    {'151': 'https://arbuz.kz/ru/almaty/catalog/cat/224905-sosiski_sardelki_bez_svininy_halal_#/'},
    # category_id -> 11:
    {'153': 'https://arbuz.kz/ru/almaty/catalog/cat/225087-deserty#/'},
    {'154': 'https://arbuz.kz/ru/almaty/catalog/cat/225088-pashtet_humus_tahini#/'},
    {'155': 'https://arbuz.kz/ru/almaty/catalog/cat/225030-tofu#/'},
]
